### ISSUE TITLE
Tooltip doesn't show information when hover over bar graph elements

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bkcharts#24]
Originally posted by gregnordin.  For original issue and full discussion, click [here](https://github.com/bokeh/bokeh/issues/3621).
--------------------------------------------------

I'm running Bokeh 0.11.0 on Mac OS X 10.10.4 with Python 3.5. I have the following code in a Jupyter Notebook:

```
from bokeh.charts import Bar, show, output_notebook
import pandas as pd

output_notebook()

data_dict = { 'numstudents' : [43, 22, 1, 
                               2, 54, 9, 
                               18, 10, 5,
                               14, 12, 3,
                               15, 11, 1,
                               14, 8, 2],
              'language' : ['Matlab','Matlab','Matlab', 
                            'C/C++','C/C++','C/C++', 
                            'Java','Java','Java',
                            'HTML/CSS','HTML/CSS','HTML/CSS',
                            'Python','Python','Python',
                            'Javascript','Javascript','Javascript'],
              'skill_level' : ['Beginner','Intermediate','Expert', 
                               'Beginner','Intermediate','Expert', 
                               'Beginner','Intermediate','Expert',
                               'Beginner','Intermediate','Expert',
                               'Beginner','Intermediate','Expert',
                               'Beginner','Intermediate','Expert']
            }

data_df = pd.DataFrame(data_dict)

p = Bar(data_df, 
        values='numstudents', 
        label='language', 
        stack='skill_level',
        legend='top_right',
        title="ECEn 360 Student Self-Reported Programming Skills",
        tooltips=[('Students:', '@numstudents'), ('Language:', '@language')]
       )
show(p)
```

The plot builds and displays just fine. The problem I am having is with the tooltip information as illustrated in the upper left of the plot image below. Note that to the right of "Students:" is "???" rather than the number of students at that skill level for that language (in this case it should be the number 9). My understanding from the documentation is that '@numstudents' should refer to the column 'numstudents', but the tooltip doesn't pick up the value from the column as it should, and as it correctly does in the case of the 'language' column. 

<img width="300" alt="screen shot 2016-01-08 at 11 07 02 pm" src="https://cloud.githubusercontent.com/assets/4380622/12237550/7d87d1c0-b83c-11e5-9928-82a500256f72.png">

**Comment by alex1sc** [comment]
I have the same issue you're talking about. 
The first field is a number and display '???', the second is also a number and display well tough!
How did you manage to make it work ?
