### ISSUE TITLE
Data streaming for charts

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bkcharts#29]
Originally posted by softengash.  For original issue and full discussion, click [here](https://github.com/bokeh/bokeh/issues/3142).
--------------------------------------------------

Using bokeh 0.10.0

For data streaming, key is to update the data source and the plot gets updated with the latest data. But how to achieve the similar thing for a chart(bar chart)?

Is there any attribute for charts using which its data (data frame or x/y) can be updated?

Kindly advise.

**Comment by chunxiangli** [comment]
I am using Bokeh 0.12.5 and encountered the same issue. What is the correct way to update data for charts, like Area, Donut?

**Comment by chunxiangli** [comment]
I found the [workaround](https://gist.github.com/rothnic/54b049eaa26fe0ec1f2d) in the original discussion. Hope to see a new feature to fix this.
