### ISSUE TITLE
HorizontalBar

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bkcharts#37]
Originally posted by birdsarah.  For original issue and full discussion, click [here](https://github.com/bokeh/bokeh/issues/1856).
--------------------------------------------------

Following on from #1780, #1836, #1851, #1852

How do people feel about a HorizontalBar variation of Bar, where the categorical axis runs on the y (and the bars run Horizontally)? 

One small naming concern is a potential confusion between: 
- Bar Graph aka Horizontal Bar Graph (we currently don't have a chart for)
- Column Graph aka Vertical Bar Graph (currently `Bar`)

I'm not sure what people use for references on this stuff, I have a few books lying around, but have only picked stuff up informally, so I have no idea what "correct" is or should be. 

But it seems that maybe being explicit and just having HorizontalBar and VerticalBar (which would imply a name change for Bar) might be useful.

**Comment by cmprince** [comment]
I would have liked this feature. I am now rendering stacked (horizontal) bar glyphs manually, and it's making referencing data for aggregation and tooltip display a real pain.

(edit: sorry, should have read the referencing issue!)
