### ISSUE TITLE
Ordering of grouped bars in bokeh.charts Bar

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bkcharts#41]
Originally posted by tobyhodges.  For original issue and full discussion, click [here](https://github.com/bokeh/bokeh/issues/2935).
--------------------------------------------------

I've been updating my scripts to take advantage of the improved charts interface in 0.10 and can't figure out how to control the order of grouped bars. I've checked the documentation/tutorials but couldn't find any information on this, sorry if I've missed it. Can someone point me in the right direction please?

Here is an example of the kind of data that I'm working with, where I'm plotting numbers for consecutive years. As you can see from the plot, I can't get the grouped bars to be arranged in the same order as the years are listed in the legend. 

```
from bokeh.charts import Bar, output_file, show
import pandas as pd

data = pd.DataFrame({'Group' :['A','A','A','A','B','B','B','B','C','C','C','C','D','D','D','D'],
                     'Year'  :['2009','2010','2011','2012','2009','2010','2011','2012','2009','2010','2011','2012','2009','2010','2011','2012'],
                     'Height':[1,2,3,4,2,2,2,2,3,0,3,0,4,3,2,1]})
fig = Bar(data, label='Group', values='Height', group='Year', legend='top_right')
output_file('chartsBarTest.html')
show(fig)
```

![chartstest](https://cloud.githubusercontent.com/assets/9694524/10221647/ef9bcd58-684f-11e5-9712-6316a93831d0.png)

**Comment by Kurt-von-Laven** [comment]
Here is my workaround from the original thread in case it helps folks. I used http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html (e.g., data.sort(group, inplace=True)) to control the order in which the groups are presented in the chart. I can't promise this works in all cases, but it seemed to solve my problem.
