### ISSUE TITLE
Histogram and color

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bkcharts#44]
Originally posted by waqarmalik.  For original issue and full discussion, click [here](https://github.com/bokeh/bokeh/issues/3716).
--------------------------------------------------

Bokeh 0.11.0

Consider the histogram example

```
from bokeh.charts import Histogram, output_file, show
from bokeh.sampledata.autompg import autompg as df

p = Histogram(df, values='hp', color='navy', title="HP Distribution")
output_file("histogram_color.html")
show(p)
```

The above example works, but if I use

```
p = Histogram(df['hp'], color='navy', title="HP Distribution")
```

I get the error

```
ValueError: cannot label index with a null key
```

Is this a known issue?

**Comment by talestsp** [comment]
same thing with 12.5
