### ISSUE TITLE
Feature: Hexbin Charts

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bkcharts#62]
Originally posted by crashMOGWAI.  For original issue and full discussion, click [here](https://github.com/bokeh/bokeh/issues/4342).
--------------------------------------------------

Have you guys discussed adding support for hexbin charts in the future?

**Comment by StevenCHowell** [comment]
Note that RBokeh has [hexbin plots](http://hafen.github.io/rbokeh/#preview).  As RBokeh uses the exact same BokehJS, one could convert the R-parts to Python, and you would have a version for the Python Bokeh (see discussion in bokeh/bokeh#4786).
