### ISSUE TITLE
Include nodes with no connections in Chord chart?

### ISSUE THREAD

**Issue by StevenCHowell** [bokeh/bkcharts#64]
I am generating a Chord chart of connections between residues of a molecule.  Here is what I currently have

![bokeh_plot 4](https://cloud.githubusercontent.com/assets/9484229/25826855/750a1b00-3416-11e7-9b20-5f82e306fb0f.png)
I have 3 issues I would like to discuss related to this

1. how could I include nodes that have no connections, i.e., so that every molecular residue is included?
2. how can I make every node have the same width on the circle?
3. how can I combine labels, e.g., strip out the "Fc" has three options after it "HC1", "HC2", and "SUG", could make the label have 3 tiers, "Fc", then "HC1"/"HC2"/"SUG", then the number?

I realize I could combine all the "FC HC1" nodes, but then is there a way to maintain the number order after (I think it would get messed up at either both ends or at least the destination end)?

I also realize that with this many nodes, the result is rather noisy, and perhaps not very useful.  Perhaps grouping the nodes and discard the numbers would be more useful.  Still exploring.

**Comment by StevenCHowell** [comment]
I would love to have the labels look more like this, where there are ticks for residue number then just have text for the categories.  ![image](https://cloud.githubusercontent.com/assets/9484229/25830097/92d860ee-3428-11e7-845b-ca29b1ef7aa7.png)

**Comment by merqurio** [comment]
You can include nodes without connections, in fact there are some in the generated graph above. Is just that their representation (size) is equally proportional to the number of edges they have.

<img width="493" alt="screen shot 2017-05-09 at 17 31 01" src="https://cloud.githubusercontent.com/assets/1485056/25858934/5abcf2b4-34dd-11e7-8bc5-16528ad655dd.png">

Just to check I understand what you're asking for:
1. New way of displaying names, where you can mix a linear scale with a name (like the example above)
1. Give every node the same width. (Maybe make this configurable ?)

This are features not included now, you might need to modify the code to generate the chart or if you're not in a hurry, we can plan them and add them to the already existing implementation (I'm quite busy till mid-June).

**Comment by bryevdv** [comment]
FYI as an aside, the new pandas version has broken `bokeh.charts` with its changed `groupby` behavior (returning `Interval` objects)

**Comment by merqurio** [comment]
So an updated is needed. I'm more than happy of updating and maintaining this chart interface. Maybe we can discuss it here and expect an update in mid-June ? That works for you ?

**Comment by StevenCHowell** [comment]
> New way of displaying names, where you can mix a linear scale with a name (like the example above)

Yes, e.g., have a name for the group, then a number for each item in the group which goes along the circular number line/semicircle.

> Give every node the same width. (Maybe make this configurable ?)

Yes. Perhaps this would be similar to you dot chord chart from #13 (originally here: bokeh/bokeh#4227).

Depending on the timing and demands of the project I'm working on, I may end up looking at how other packages ([nxviz](https://github.com/ericmjl/nxviz), [plotly](https://plot.ly/python/filled-chord-diagram/),  or some R packages, [circlize: chordDiagram()](http://zuguang.de/circlize_book/book/the-chorddiagram-function.html) or [chorddiag](https://github.com/mattflor/chorddiag)) implement their chord charts.  This could provide more concrete ideas.
