### ISSUE TITLE
Require pandas

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bkcharts#72]
Seems that `bkcharts` is importing `pandas` all over the place. Given this, should `pandas` just be an install dependency of `bkcharts`?

ref: https://github.com/bokeh/bkcharts/search?p=2&q=pandas&type=&utf8=%E2%9C%93

**Comment by bryevdv** [comment]
Yes,  additionally `bkcharts` should depend on `bokeh` not the other way around, but these things can't happen until the `bkcharts` compatibility shim in the core Bokeh library is finally removed.

**Comment by jakirkham** [comment]
I think I understand why `bkcharts` and `bokeh` are complicated.

However I don't understand why this complexity transfers to adding `pandas` as a dependency. It seems that `bkcharts` could depend on `pandas` and so could `bokeh` if necessary. It's not really a cyclic dependency of either, right? Or am I missing something?

**Comment by bryevdv** [comment]
Bokeh currently depends on `bkacharts` (for the compat shim to "just work"). If `bkcharts` adds pandas as a dependency right now, then Bokeh will pick that dependency up transitively.
