### ISSUE TITLE
Cyclic requirement on bokeh

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bkcharts#73]
Seems there is an effective cyclic requirement on `bokeh`. Namely `bokeh` requires [`bkcharts`]( https://github.com/bokeh/bokeh/blob/0.12.6/setup.py#L98 ). However `bkcharts` uses `bokeh` for [example]( https://github.com/bokeh/bkcharts/blob/0.2/bkcharts/properties.py#L13-L15 ). It seems based on how this package is described and setup it should depend on `bokeh`. Though this is a tricky thing given `bokeh`'s dependency on it. How do we resolve this? What is the long term plan?

**Comment by bryevdv** [comment]
Bokeh will drop the `bkcharts` combat shim on Bokeh 1.0

**Comment by jakirkham** [comment]
To be clear, you are referring to [this]( https://github.com/bokeh/bokeh/blob/0.12.6/bokeh/charts/__init__.py ) as the compat shim?

To make sure I understand this correctly, `bkcharts` is basically a refactoring of existing `bokeh` content. However to not break the API `bokeh` must rely on `bkcharts` near term. In the long term (i.e. 1.0), the API can be broken meaning the shim can be dropped and `bkcharts` will become a proper downstream user of `bokeh`. Is this correct?

**Comment by bryevdv** [comment]
Yes, that is exactly correct. If there is something that can be done differently or better in the short term, please let me know. I should add that after Bokeh 1.0 `bkcharts` will probably also not be released to `defaults` any longer (just the bokeh channel and C-F)
