### ISSUE TITLE
runtime error:    from bokeh.models.scales import CategoricalScale ImportError: No module named scales

### ISSUE THREAD

**Issue by dbwrangler** [bokeh/bkcharts#76]
I'm testing out bkcharts (currently I use high level charts in 0.12.5).

pip freeze:
bkcharts==0.2
bokeh==0.12.6

I am trying your 'stacked bar chart example, and get error:

python app2.py
Traceback (most recent call last):
  File "app2.py", line 1, in <module>
    from bkcharts import Bar, output_file, show
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bkcharts/__init__.py", line 8, in <module>
    from .chart import Chart, defaults
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/bkcharts/chart.py", line 22, in <module>
    from bokeh.models.scales import CategoricalScale

The code is the same as your example directory:

from bkcharts import Bar, output_file, show
from bkcharts.attributes import cat, color
from bkcharts.operations import blend
from bkcharts.utils import df_from_json
from bokeh.sampledata.olympics2014 import data

# utilize utility to make it easy to get json/dict data converted to a dataframe
df = df_from_json(data)

# filter by countries with at least one medal and sort by total medals
df = df[df['total'] > 0]
df = df.sort_values(by="total", ascending=False)

bar = Bar(df,
          values=blend('bronze', 'silver', 'gold', name='medals', labels_name='medal'),
          label=cat(columns='abbr', sort=False),
          stack=cat(columns='medal', sort=False),
          color=color(columns='medal', palette=['SaddleBrown', 'Silver', 'Goldenrod'],
                      sort=False),
          legend='top_right',
          title="Medals per Country, Sorted by Total Medals",
          tooltips=[('medal', '@medal'), ('country', '@abbr')])

output_file("stacked_bar.html", title="stacked_bar.py example")

show(bar)

Any help/clue how to fix?

thanks!

**Comment by bryevdv** [comment]
The short answer is that `bkcharts` is effectively unmaintained at this point, so the best solution to keep using it is to stay on Bokeh `0.12.5`. 

The *much better* answer is to switch to HoloViews, which is a very high level library for data exploration that integrates tightly with bokeh to create great interactive visalizations with very small amounts of code. It's actively maintained, and already better than `bkcharts`: http://holoviews.org/ Going forward, we (the Bokeh core team) will be endorsing HoloViews as the officially recommended High Level API on top of Bokeh.

**Comment by dbwrangler** [comment]
bryevdv - thanks, holoviews looks very interesting - will spike it now.
