### ISSUE TITLE
ImportError: cannot import name 'DEFAULT_PALETTE'

### ISSUE THREAD

**Issue by rgaiacs** [bokeh/bkcharts#79]
When Travis CI runs my tests I got

~~~
File "/home/travis/build/softwaresaved/lowfat/lowfat/views.py", line 16, in <module>
    from bkcharts import Bar, Histogram
  File "/home/travis/virtualenv/python3.6-dev/lib/python3.6/site-packages/bkcharts/__init__.py", line 5, in <module>
    from bokeh.plotting.helpers import DEFAULT_PALETTE; DEFAULT_PALETTE
ImportError: cannot import name 'DEFAULT_PALETTE'
~~~

**Comment by bryevdv** [comment]
FYI, from the project README:

> bkcharts is currently unmaintained. For actively developed, supported, very high level charting on top of Bokeh, see the HoloViews project: http://holoviews.org/

Additionally, many types of categorical (bar, scatter, heat map) plots there were previously difficult or hard with core Bokeh are now simple with `bokeh.plotting`:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

**Comment by rgaiacs** [comment]
@bryevdv Thanks for the information. A few months ago I got

> BokehDeprecationWarning: The bokeh.charts API has moved to a separate 'bkcharts' package.

on my tests so I made the change. I will use `bokeh.plotting` or HoloViews. Feel free to close this issue.

**Comment by jbrockmendel** [comment]
FWIW I made my way here debugging the same error, changed over to bkcharts because of the same `BokehDeprecationWarning`.
