### ISSUE TITLE
[bar chart] Rotate Tap Tool effect?

### ISSUE THREAD

**Issue by nickleman** [bokeh/bkcharts#80]
I have a vertical bar chart with lots of groups representing hours worked on a project. They have data for each week. The hours are on the y axis and the week number is the x axis.  I would like the to use the tap tool to highlight that specific project over all the weeks. However, when I set it up it highlights all the projects in the same week instead, I would like to rotate that capability. Please let me know if this doesn't make sense. If need be, I can provide a screenshot or two.

**Comment by bryevdv** [comment]
FYI, from the project README:

> bkcharts is currently **unmaintained**. For actively developed, supported, very high level charting on top of Bokeh, see the HoloViews project: http://holoviews.org/

Additionally, many types of categorical (bar, scatter, heat map) plots there were previously difficult or hard with core Bokeh are now simple with `bokeh.plotting`:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

**Comment by nickleman** [comment]
I'm using Figure.vbar from bokeh.plotting. Ahh, I think I put this in the wrong place. Should have been bokeh/bokeh I think.

**Comment by bryevdv** [comment]
yes however support and usage questions should not go in the tracker, please use the public mailing list for support:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh
